version: '3.3'

networks:
  opensis_network:

volumes:
  db_data:
  openSIS:
  prometheus_data:
  grafana_data:

services:
  database:
    image: mariadb:10.5
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: openSIS
      MYSQL_USER: openSIS_rw
      MYSQL_PASSWORD: Op3nS!S
    volumes:
      - db_data:/var/lib/mysql
      - ./openSIS-Classic/MYSQL/mysql-init:/docker-entrypoint-initdb.d
      - ./openSIS-Classic/MYSQL/mysql-config/strict_mode.cnf:/etc/mysql/conf.d/strict_mode.cnf
    ports:
      - "3307:3306"
    networks:
      - opensis_network

  frontend:
    image: a1helene-opensis-image:latest
    container_name: frontend
    depends_on:
      - database
    ports:
      - "8090:80"
      - "80:80"
    networks:
      - opensis_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /student_home/OpenSIS/S9-project-01-Updated-OpenSIS/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9091:9090"
    networks:
      - opensis_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - opensis_network

